Fix deprecation warnings and update deps
browserify/crypto-browserify pull request #200
Opened 2021-01-24 19:32 UTC by coltongit

2021-01-24 19:34 UTC, ljharb approved these changes
LGTM, thanks. should be a patch update

2021-01-24 19:38 UTC, coltongit commented
Minor note @ljharb
Node 0.1x builds broke because https://github.com/crypto-browserify/publicEncrypt grabs a later version of parse-asn1 than what was originally used for the last build 3 years ago.

2021-01-24 19:42 UTC, ljharb commented
0.1? Or 0.10?

2021-01-24 19:42 UTC, coltongit commented
> 
> 
> 0.1? Or 0.10?

0.11/0.12

2021-01-24 19:54 UTC, coltongit commented
@ljharb
I figured out what was erroring out the build originally for Saucelabs. Some of the ports weren't forwarded for some strange reason
```
Error: connection refused: localtunnel.me:41870 (check your firewall settings)
Error: connection refused: localtunnel.me:34242 (check your firewall settings)
Error: connection refused: localtunnel.me:35354 (check your firewall settings)
```
These are from the last build from 3 years ago

2021-01-24 19:54 UTC, ljharb commented
gotcha, but they’ll pass now?

2021-01-24 19:55 UTC, coltongit commented
> 
> 
> gotcha, but they’ll pass now?

If of course you have those issues fixed, then yes, this will just fine

2021-01-24 19:57 UTC, coltongit commented
Pretty much, if the parse-asn1 issue is fixed along with those connection refused issues, this will pass Travis CI

2021-01-24 20:28 UTC, coltongit commented
> 
> 
> gotcha, but they’ll pass now? If not, can we pin parse-asn1 so they do?

Yep! 3.1.0 iirc is the last version that worked

2021-02-02 13:51 UTC, coltongit commented
Any progress updates on this so far? Has the Saucelabs stuff been figured out yet?

2021-11-25 16:03 UTC, cwc972135903 commented
do you how to implement the generateKeyPair

2022-05-04 07:07 UTC, markhughes requested changes
`randomFill` and `randomFillSync` are implemented :)

2022-05-04 07:07 UTC, markhughes commented on README.md
> +* randomFillSync
`randomFill` and `randomFillSync` are implemented, we can remove this from the README

2022-05-04 07:07 UTC, markhughes commented on example/bundle.js
> +  'randomFillSync',
`randomFill` and `randomFillSync` are implemented, we can remove this from the error message array

2023-08-12 18:13 UTC, closed without merging

2023-08-18 19:58 UTC, rawr51919 commented
this PR will return, eventually, just was cleaning out old repos, may merge this and #201 together into one PR